GET http://localhost:5000/api/threads

###

GET http://localhost:5000/api/threads/5f4b77dd4b595f438887e53d HTTP/1.1

###

POST http://localhost:5000/api/threads HTTP/1.1
content-type: application/json

{
    "title": "Fast, unopinionated, minimalist web framework for Node.js",
    "body": "Express is a minimal and flexible Node.js web application"
}

###

PATCH http://localhost:5000/api/threads/5f4a2a32044d094c7870f1e4 HTTP/1.1
content-type: application/json

{
    "title": "Fast, unopinionated, minimalist web framework for Node.js",
    "body": "Express is a minimal and flexible Node.js web application"
}

###

POST http://localhost:5000/api/threads/reply HTTP/1.1
content-type: application/json

{
    "_thread": "5f6731ac27af1c28687a1de4",
    "body": "Reply body test"
}

###

GET http://localhost:5000/api/threads/test/1